### ISSUE TITLE
lighthouse checks not completing

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-hugo-themes#293]
### Steps to Reproduce

Create a PR in `ocw-hugo-themes`

### Expected Behavior

The lighthouse check completes successfully

### Actual Behavior

It does not

### Stacktrace

```
lighthouse-check:
 Error: ENOENT: no such file or directory, open '/tmp/artifacts/report-1638292972865.html'
    at Object.openSync (fs.js:497:3)
    at Object.writeFileSync (fs.js:1528:35)
    at exports.default (/node_modules/@foo-software/lighthouse-persist/dist/lighthousePersist.js:161:26)
    at async localLighthouse (/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:81:7)
    at async getLocalLighthouseResultsWithRetries (/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:122:29)
    at async _default (/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:227:35)
    at async /node_modules/@foo-software/lighthouse-check/dist/lighthouseCheck.js:175:32 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/tmp/artifacts/report-1638292972865.html'
}
```

**Comment by gumaerc** [comment]
After some investigation I have a hunch this might be an upstream issue with the Github action we're using for Lighthouse checks.  I created an issue here: https://github.com/foo-software/lighthouse-check-action/issues/68
